version: "3"
services:
  pg01:
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    volumes:
    - pg01:/data/postgres
    ports:
    - 5432:5432
    networks:
    - pg01
    restart: unless-stopped
  redis01:
    image: redis:4.0.5-alpine
    command: redis-server --requirepass "redispass"
    volumes:
    - redis01:/data
    ports:
    - 6379:6379
    networks:
    - redis01
  mysql01:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: myalbum
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_PASSWORD: mypass
      MYSQL_USER: mysql
    volumes:
    - mysql01:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
    - mysql01
    restart: unless-stopped
networks:
  pg01:
    driver: bridge
  mysql01:
    driver: bridge
  redis01: null
volumes:
  pg01: null
  redis01: null
  mysql01: null
