version: "3"
services:
  pg01:
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES: postgres
      POSTGRES_PASSWORD: pgpass
    volumes:
    - pg01:/data/postgres
    ports:
    - 5432:5432
    networks:
    - pg01
    restart: unless-stopped
  redis:
    image: redis:4.0.5-alpine
    command: redis-server --requirepass "redispass"
    volumes:
    - redis:/data
    ports:
    - 6379:6379
    networks:
    - redis
networks:
  pg01:
    driver: bridge
  redis: null
volumes:
  pg01: null
  redis: null
