version: "3"
services:
  postgres:
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-pgpass}
    volumes:
    - postgres:/data/postgres
    ports:
    - ${PG_PORT:-5432}:5432
    networks:
    - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: null
